linters:
  enable-all: true
  disable:
    - interfacer
    - gas
    - megacheck
    - structcheck
    - staticcheck
    - varnamelen
    - gochecknoglobals
    - scopelint
    - funlen
    - godox
    - exhaustivestruct
    - goerr113
    - wsl
    - nlreturn
    - gomnd
    - paralleltest
    - wrapcheck
    - testpackage
    - golint
    - maligned
    - gofumpt
    - forbidigo
    - exhaustruct
    - nonamedreturns
    - tagliatelle
    - gomoddirectives
    - ifshort
    - ireturn
    - nosnakecase
    - deadcode
    - varcheck
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

issues:
  exclude-use-default: false
  max-same-issues: 0
